# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c48f623b50c7755d3a121db4e6c3b145fe7dc5acdb6fd2bf4751e89c6e983ee46e49ea37e079ac1c5fb62fe73a8d60643a115ad61ebab98a211fa3e36a96036

test:
  secret_key_base: 7e2b1de02ed4b3670dc7a3c8013fa166bbbcc375324bc5a96846364550145acbdb41bca26a6673705a9fea7ac68ef3fa2904861905ab8673b62475b5bb2563b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
